### ISSUE TITLE
Consider ways to disable registrations when ID is specified in [register_form]

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-limited-quantity-available#1]
If someone specifies the ID in the [register_form] because they're using a custom landing page or something like that, we need a good, smooth way to disable registrations for that. Not sure what best way is just yet, if there's any smooth way at all. May need some adjustments to RCP core. Maybe could override the template. Also could fire off an email to the site admin when total registrations reached.

**Comment by mindctrl** [comment]
@pippinsplugins thoughts on this approach?

**Comment by pippinsplugins** [comment]
A few requests put on the PR. Otherwise I like it.

**Comment by mindctrl** [comment]
@pippinsplugins updated PR.

**Comment by mindctrl** [comment]
@pippinsplugins filters added.

**Comment by pippinsplugins** [comment]
Looks good.
