### ISSUE TITLE
Update plugin description

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-limited-quantity-available#16]
Current:

> Control the number of times a subscription can be purchased.

Proposed:

> Control the number of times a membership level can be purchased.

**Comment by nosegraze** [comment]
PR: #17

Also updated readme to replace `subscription` with `membership`.

**Comment by nosegraze** [comment]
Updated to also replace `subscription` with `membership` in the admin settings.

**Comment by misulicus** [comment]
@nosegraze other than a few typos in there its all good.
