### ISSUE TITLE
Increase width of Membership Level setting input field

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-limited-quantity-available#18]
![2019-10-23 16_26_57](https://user-images.githubusercontent.com/6324272/67409077-f7633000-f5b1-11e9-8c1b-2c83b8ba624c.png)

It's not terribly small, but I think we should increase it slightly to match the same width as the signup fee field. That'll take it from `60px` to `100px`.

**Comment by nosegraze** [comment]
PR: #19

![2019-10-23 16_30_31](https://user-images.githubusercontent.com/6324272/67409455-81ab9400-f5b2-11e9-8c26-fca8b8cb10de.png)

I also fixed the label for this field -- the `for` attribute was referencing an incorrect ID.

**Comment by misulicus** [comment]
@nosegraze this one is good to go
