### ISSUE TITLE
Count existing members of existing levels

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-limited-quantity-available#2]
If someone edits an existing level and defines a limit, the existing subscribers of that level do not count towards the total quantity available. It only counts going forward. To make things more clear, we should count existing subscribers towards the total in these cases.

**Comment by mindctrl** [comment]
@pippinsplugins ready for testing and review.

**Comment by pippinsplugins** [comment]
PR looks good but it made me think of something.

Are we counting the total units sold over all time or just the currently-active count? The PR will be for all time. If that's intended, that seems fine to me!

**Comment by mindctrl** [comment]
I intended for all time, and I think most people would. I'm sure someone might ask for currently active only, but then someone else would ask for all time. I feel like if someone wants active only, they can figure out how many they've sold all time and do the math themselves.

**Comment by pippinsplugins** [comment]
:+1:
